// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkfGflr1duC2zOVV4eD_5_0o90lHybZ2o',
    appId: '1:203832978252:web:835cbd3350e13185893de9',
    messagingSenderId: '203832978252',
    projectId: 'grocery-44d37',
    authDomain: 'grocery-44d37.firebaseapp.com',
    storageBucket: 'grocery-44d37.firebasestorage.app',
    measurementId: 'G-BCS8QNMSFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHB4xEVVfgkTMhmNL-49HoERlAucP6xf8',
    appId: '1:203832978252:android:5a63bdb7dda17834893de9',
    messagingSenderId: '203832978252',
    projectId: 'grocery-44d37',
    storageBucket: 'grocery-44d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-2NhuF2Q3fr8YEGhsm9cPztZ81qougoE',
    appId: '1:203832978252:ios:6504d1544101f10c893de9',
    messagingSenderId: '203832978252',
    projectId: 'grocery-44d37',
    storageBucket: 'grocery-44d37.firebasestorage.app',
    iosBundleId: 'com.example.grocery',
  );
}
